on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: macos-14
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            -   name: Use Node.js
                uses: actions/setup-node@v4.0.2
                with:
                    node-version: 16.20.2

            - name: Install dependencies
              run: npm ci --legacy-peer-deps

            - name: Build app (macOS x64)
              run: npm run build-mac-x64

            - name: Build app (macOS arm64)
              run: npm run build-mac-arm64