on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: macos-14
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            - name: Use Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  # Node 14 isn't compatible with MacOS 14 ARM64
                  # TODO: Update app to at least Node 18
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Build app (macOS x64)
              run: npm run build-mac-x64

            - name: Build app (macOS arm64)
              run: npm run build-mac-arm64